import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    spacing: {
      0: "0px",
      px: "1px",
      0.5: "2px",
      1: "4px",
      1.5: "6px",
      2: "8px",
      2.5: "10px",
      3: "12px",
      3.5: "14px",
      4: "16px",
      5: "20px",
      6: "24px",
      7: "28px",
      8: "32px",
      9: "36px",
      10: "40px",
      11: "44px",
      12: "48px",
      14: "56px",
      16: "64px",
      20: "80px",
      24: "96px",
      28: "112px",
      32: "128px",
      36: "144px",
      40: "160px",
      44: "176px",
      48: "192px",
      52: "208px",
      56: "224px",
      60: "240px",
      64: "256px",
      72: "288px",
      80: "320px",
      96: "384px",
    },
    extend: {
      colors: {
        codey: {
          "bg-deep": "#050a12",
          "bg-surface": "#0a1628",
          "bg-raised": "#111f38",
          border: "#1e3a5f",
          "blue-primary": "#2563eb",
          "blue-light": "#60a5fa",
          "blue-subtle": "#1e3a5f",
          "text-primary": "#f1f5f9",
          "text-secondary": "#94a3b8",
          "text-muted": "#475569",
          green: "#22c55e",
          yellow: "#eab308",
          red: "#ef4444",
          "code-bg": "#0a1628",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        mono: [
          "var(--font-jetbrains)",
          "JetBrains Mono",
          "Consolas",
          "monospace",
        ],
      },
      fontSize: {
        metadata: ["12px", { lineHeight: "16px" }],
        secondary: ["14px", { lineHeight: "20px" }],
        body: ["16px", { lineHeight: "24px" }],
        subheading: ["18px", { lineHeight: "28px" }],
        heading: ["24px", { lineHeight: "32px" }],
        "page-title": ["32px", { lineHeight: "40px" }],
        hero: ["48px", { lineHeight: "1.1" }],
      },
      borderRadius: {
        sm: "4px",
        md: "6px",
        lg: "8px",
        xl: "12px",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(0, 0, 0, 0.4)",
        md: "0 4px 12px rgba(0, 0, 0, 0.5)",
        lg: "0 8px 24px rgba(0, 0, 0, 0.6)",
        xl: "0 20px 40px rgba(0, 0, 0, 0.8)",
        glow: "0 0 0 3px rgba(37, 99, 235, 0.2)",
      },
      animation: {
        "fade-in": "fade-in 150ms ease",
        "modal-in": "modal-in 150ms ease",
        "critical-pulse": "critical-pulse 2s infinite",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "modal-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "critical-pulse": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.3)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
