import { FileText } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-codey-bg">
      <div className="mx-auto max-w-3xl px-4 py-16">
        <div className="flex items-center gap-3">
          <FileText className="h-6 w-6 text-codey-green" />
          <h1 className="text-2xl font-bold text-codey-text">Terms of Service</h1>
        </div>
        <p className="mt-2 text-sm text-codey-text-muted">
          Last updated: March 27, 2026
        </p>

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-codey-text-dim">
          <section>
            <h2 className="text-lg font-semibold text-codey-text">What Codey Is</h2>
            <p className="mt-2">
              Codey is an AI-powered code generation and analysis platform operated by Qira LLC.
              You provide plain-language prompts, and Codey generates production-ready source code,
              analyzes structural health, and stores
              your code in a versioned vault. Codey is a tool, not a replacement for a developer.
              You are responsible for reviewing, testing, and deploying any code Codey generates.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-codey-text">Credits and Payment</h2>
            <p className="mt-2">
              Codey operates on a credit-based system. Free accounts receive a monthly credit
              allocation. Paid plans (Pro, Team) include higher credit limits and additional
              features. Credits purchased as top-ups are non-refundable. Monthly plan credits
              refresh at the start of each billing cycle and do not roll over. If your subscription
              is cancelled, unused credits expire at the end of the billing period.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-codey-text">Ownership of Output</h2>
            <p className="mt-2">
              You own the code that Codey generates for you. Qira LLC claims no ownership or
              license to your prompts, generated code, or project data. You are free to use,
              modify, distribute, and commercialize all output without restriction or attribution.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-codey-text">No Warranty on Generated Code</h2>
            <p className="mt-2">
              Code generated by Codey is provided &ldquo;as is&rdquo; without warranty of any kind.
              Qira LLC is not responsible for bugs, security vulnerabilities, performance issues,
              data loss, or any other problems that arise from using code that Codey produces. You
              should review all generated code before deploying it to production environments.
              Health scores are structural analysis indicators, not guarantees of correctness.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-codey-text">Acceptable Use</h2>
            <p className="mt-2">
              You agree not to use Codey to generate code intended for malicious purposes,
              including but not limited to: malware, phishing tools, exploits, spam systems,
              surveillance software, or any code designed to harm individuals or organizations.
              Qira LLC reserves the right to terminate accounts that violate this policy without
              refund.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-codey-text">Account Termination</h2>
            <p className="mt-2">
              You may delete your account at any time from the Settings page. Qira LLC may
              suspend or terminate your account if you violate these terms. Upon termination,
              your code vault data will be deleted within 30 days. Active subscriptions will
              not be refunded upon termination for violations.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-codey-text">Limitation of Liability</h2>
            <p className="mt-2">
              To the maximum extent permitted by law, Qira LLC shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages, including loss
              of profits, data, or business opportunities, arising from your use of Codey.
              Our total liability shall not exceed the amount you have paid to Qira LLC in the
              twelve months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-codey-text">Changes to Terms</h2>
            <p className="mt-2">
              We may update these terms from time to time. Continued use of Codey after changes
              constitutes acceptance. We will notify registered users of material changes by email.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-codey-text">Governing Law</h2>
            <p className="mt-2">
              These terms are governed by the laws of the State of Arizona, United States, without
              regard to conflict of law principles. Any disputes arising from these terms shall be
              resolved in the courts of Maricopa County, Arizona.
            </p>
          </section>

          <section className="rounded-lg border border-codey-border bg-codey-card p-4">
            <p className="text-xs text-codey-text-muted">
              Qira LLC &middot; Phoenix, Arizona &middot; Questions? Contact{" "}
              <a href="mailto:legal@codey.ai" className="text-codey-green hover:underline">
                legal@codey.ai
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
