"""Template Library — pre-defined project templates for common application types."""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


class TemplateLibrary:
    """Collection of project templates for fast-starting common application types.

    Each template defines the stack, file tree, phases, and credit estimates
    so the planner can skip clarification and jump straight to building.
    """

    TEMPLATES: dict[str, dict[str, Any]] = {
        "saas_starter": {
            "name": "SaaS Starter",
            "description": "Full-stack SaaS boilerplate with auth, billing, dashboard, and API",
            "estimated_credits": {"min": 35, "max": 60},
            "stack": {
                "frontend": "Next.js 14 (App Router) + TypeScript + Tailwind CSS",
                "backend": "FastAPI + Python 3.12",
                "database": "PostgreSQL + SQLAlchemy + Alembic",
                "auth": "JWT + OAuth (GitHub, Google)",
                "billing": "Stripe Subscriptions",
                "deployment": "Docker + Docker Compose",
            },
            "file_tree": {
                "backend/pyproject.toml": "config",
                "backend/alembic.ini": "config",
                "backend/app/__init__.py": "config",
                "backend/app/config.py": "config",
                "backend/app/database.py": "config",
                "backend/app/models/__init__.py": "model",
                "backend/app/models/user.py": "model",
                "backend/app/models/subscription.py": "model",
                "backend/app/schemas/user.py": "schema",
                "backend/app/schemas/auth.py": "schema",
                "backend/app/services/auth_service.py": "service",
                "backend/app/services/billing_service.py": "service",
                "backend/app/services/user_service.py": "service",
                "backend/app/api/__init__.py": "config",
                "backend/app/api/auth.py": "router",
                "backend/app/api/users.py": "router",
                "backend/app/api/billing.py": "router",
                "backend/app/api/health.py": "router",
                "backend/app/middleware/auth.py": "middleware",
                "backend/app/main.py": "router",
                "backend/tests/test_auth.py": "test",
                "backend/tests/test_billing.py": "test",
                "backend/Dockerfile": "docker",
                "frontend/package.json": "config",
                "frontend/tsconfig.json": "config",
                "frontend/tailwind.config.ts": "config",
                "frontend/app/layout.tsx": "page",
                "frontend/app/page.tsx": "page",
                "frontend/app/login/page.tsx": "page",
                "frontend/app/dashboard/page.tsx": "page",
                "frontend/app/dashboard/layout.tsx": "page",
                "frontend/app/billing/page.tsx": "page",
                "frontend/components/ui/Button.tsx": "component",
                "frontend/components/ui/Card.tsx": "component",
                "frontend/components/ui/Input.tsx": "component",
                "frontend/components/AuthForm.tsx": "component",
                "frontend/components/DashboardNav.tsx": "component",
                "frontend/hooks/useAuth.ts": "hook",
                "frontend/hooks/useApi.ts": "hook",
                "frontend/lib/api.ts": "service",
                "frontend/Dockerfile": "docker",
                "docker-compose.yml": "docker",
                "README.md": "static",
            },
            "phases": [
                {
                    "name": "Project Setup & Config",
                    "files": [
                        "backend/pyproject.toml", "backend/alembic.ini",
                        "backend/app/__init__.py", "backend/app/config.py",
                        "backend/app/database.py", "frontend/package.json",
                        "frontend/tsconfig.json", "frontend/tailwind.config.ts",
                    ],
                    "description": "Configuration files and project scaffolding",
                },
                {
                    "name": "Data Layer",
                    "files": [
                        "backend/app/models/__init__.py", "backend/app/models/user.py",
                        "backend/app/models/subscription.py",
                        "backend/app/schemas/user.py", "backend/app/schemas/auth.py",
                    ],
                    "description": "Database models and API schemas",
                },
                {
                    "name": "Business Logic",
                    "files": [
                        "backend/app/services/auth_service.py",
                        "backend/app/services/billing_service.py",
                        "backend/app/services/user_service.py",
                        "backend/app/middleware/auth.py",
                    ],
                    "description": "Core services and middleware",
                },
                {
                    "name": "API Layer",
                    "files": [
                        "backend/app/api/__init__.py", "backend/app/api/auth.py",
                        "backend/app/api/users.py", "backend/app/api/billing.py",
                        "backend/app/api/health.py", "backend/app/main.py",
                    ],
                    "description": "REST API endpoints and app entrypoint",
                },
                {
                    "name": "Frontend Foundation",
                    "files": [
                        "frontend/lib/api.ts", "frontend/hooks/useAuth.ts",
                        "frontend/hooks/useApi.ts",
                        "frontend/components/ui/Button.tsx",
                        "frontend/components/ui/Card.tsx",
                        "frontend/components/ui/Input.tsx",
                    ],
                    "description": "API client, hooks, and UI primitives",
                },
                {
                    "name": "Frontend Pages",
                    "files": [
                        "frontend/components/AuthForm.tsx",
                        "frontend/components/DashboardNav.tsx",
                        "frontend/app/layout.tsx", "frontend/app/page.tsx",
                        "frontend/app/login/page.tsx",
                        "frontend/app/dashboard/page.tsx",
                        "frontend/app/dashboard/layout.tsx",
                        "frontend/app/billing/page.tsx",
                    ],
                    "description": "Application pages and composed components",
                },
                {
                    "name": "Tests & Deployment",
                    "files": [
                        "backend/tests/test_auth.py", "backend/tests/test_billing.py",
                        "backend/Dockerfile", "frontend/Dockerfile",
                        "docker-compose.yml", "README.md",
                    ],
                    "description": "Test suites and deployment configuration",
                },
            ],
        },
        "rest_api": {
            "name": "REST API",
            "description": "Production-grade REST API with auth, CRUD, pagination, and tests",
            "estimated_credits": {"min": 15, "max": 30},
            "stack": {
                "backend": "FastAPI + Python 3.12",
                "database": "PostgreSQL + SQLAlchemy + Alembic",
                "auth": "JWT Bearer tokens",
                "testing": "pytest + httpx",
                "deployment": "Docker",
            },
            "file_tree": {
                "pyproject.toml": "config",
                "alembic.ini": "config",
                "app/__init__.py": "config",
                "app/config.py": "config",
                "app/database.py": "config",
                "app/models/__init__.py": "model",
                "app/models/user.py": "model",
                "app/models/item.py": "model",
                "app/schemas/user.py": "schema",
                "app/schemas/item.py": "schema",
                "app/schemas/common.py": "schema",
                "app/services/auth_service.py": "service",
                "app/services/item_service.py": "service",
                "app/api/auth.py": "router",
                "app/api/items.py": "router",
                "app/api/health.py": "router",
                "app/middleware/auth.py": "middleware",
                "app/main.py": "router",
                "tests/conftest.py": "test",
                "tests/test_auth.py": "test",
                "tests/test_items.py": "test",
                "Dockerfile": "docker",
                "docker-compose.yml": "docker",
            },
            "phases": [
                {"name": "Config", "files": ["pyproject.toml", "alembic.ini", "app/__init__.py", "app/config.py", "app/database.py"], "description": "Project configuration"},
                {"name": "Models & Schemas", "files": ["app/models/__init__.py", "app/models/user.py", "app/models/item.py", "app/schemas/user.py", "app/schemas/item.py", "app/schemas/common.py"], "description": "Data layer"},
                {"name": "Services", "files": ["app/services/auth_service.py", "app/services/item_service.py", "app/middleware/auth.py"], "description": "Business logic"},
                {"name": "API", "files": ["app/api/auth.py", "app/api/items.py", "app/api/health.py", "app/main.py"], "description": "Endpoints"},
                {"name": "Tests & Deploy", "files": ["tests/conftest.py", "tests/test_auth.py", "tests/test_items.py", "Dockerfile", "docker-compose.yml"], "description": "Tests and deployment"},
            ],
        },
        "react_app": {
            "name": "React Application",
            "description": "Modern React app with routing, state management, API integration, and tests",
            "estimated_credits": {"min": 15, "max": 28},
            "stack": {
                "frontend": "React 18 + TypeScript + Vite",
                "styling": "Tailwind CSS",
                "state": "Zustand",
                "routing": "React Router v6",
                "testing": "Vitest + React Testing Library",
            },
            "file_tree": {
                "package.json": "config",
                "tsconfig.json": "config",
                "vite.config.ts": "config",
                "tailwind.config.ts": "config",
                "postcss.config.js": "config",
                "index.html": "static",
                "src/main.tsx": "config",
                "src/App.tsx": "page",
                "src/types/index.ts": "schema",
                "src/lib/api.ts": "service",
                "src/store/authStore.ts": "service",
                "src/store/appStore.ts": "service",
                "src/hooks/useAuth.ts": "hook",
                "src/hooks/useApi.ts": "hook",
                "src/components/ui/Button.tsx": "component",
                "src/components/ui/Card.tsx": "component",
                "src/components/ui/Input.tsx": "component",
                "src/components/ui/Modal.tsx": "component",
                "src/components/Layout.tsx": "component",
                "src/components/Navbar.tsx": "component",
                "src/pages/Home.tsx": "page",
                "src/pages/Login.tsx": "page",
                "src/pages/Dashboard.tsx": "page",
                "src/pages/NotFound.tsx": "page",
                "src/__tests__/App.test.tsx": "test",
                "src/__tests__/auth.test.ts": "test",
            },
            "phases": [
                {"name": "Config", "files": ["package.json", "tsconfig.json", "vite.config.ts", "tailwind.config.ts", "postcss.config.js", "index.html", "src/main.tsx"], "description": "Project setup"},
                {"name": "Types & API", "files": ["src/types/index.ts", "src/lib/api.ts", "src/store/authStore.ts", "src/store/appStore.ts", "src/hooks/useAuth.ts", "src/hooks/useApi.ts"], "description": "Data layer"},
                {"name": "UI Components", "files": ["src/components/ui/Button.tsx", "src/components/ui/Card.tsx", "src/components/ui/Input.tsx", "src/components/ui/Modal.tsx", "src/components/Layout.tsx", "src/components/Navbar.tsx"], "description": "Reusable components"},
                {"name": "Pages", "files": ["src/App.tsx", "src/pages/Home.tsx", "src/pages/Login.tsx", "src/pages/Dashboard.tsx", "src/pages/NotFound.tsx"], "description": "Application pages"},
                {"name": "Tests", "files": ["src/__tests__/App.test.tsx", "src/__tests__/auth.test.ts"], "description": "Test suites"},
            ],
        },
        "cli_tool": {
            "name": "CLI Tool",
            "description": "Python CLI application with rich output, config management, and tests",
            "estimated_credits": {"min": 8, "max": 15},
            "stack": {
                "language": "Python 3.12",
                "cli": "Click + Rich",
                "config": "TOML + Pydantic",
                "testing": "pytest",
                "packaging": "setuptools / pyproject.toml",
            },
            "file_tree": {
                "pyproject.toml": "config",
                "src/cli/__init__.py": "config",
                "src/cli/main.py": "router",
                "src/cli/config.py": "config",
                "src/cli/commands/__init__.py": "config",
                "src/cli/commands/init.py": "router",
                "src/cli/commands/run.py": "router",
                "src/cli/commands/config_cmd.py": "router",
                "src/cli/core/engine.py": "service",
                "src/cli/core/output.py": "service",
                "src/cli/utils/files.py": "util",
                "tests/test_commands.py": "test",
                "tests/test_engine.py": "test",
                "tests/conftest.py": "test",
                "README.md": "static",
            },
            "phases": [
                {"name": "Config", "files": ["pyproject.toml", "src/cli/__init__.py", "src/cli/config.py", "src/cli/commands/__init__.py"], "description": "Setup"},
                {"name": "Core", "files": ["src/cli/core/engine.py", "src/cli/core/output.py", "src/cli/utils/files.py"], "description": "Core logic"},
                {"name": "Commands", "files": ["src/cli/main.py", "src/cli/commands/init.py", "src/cli/commands/run.py", "src/cli/commands/config_cmd.py"], "description": "CLI commands"},
                {"name": "Tests", "files": ["tests/conftest.py", "tests/test_commands.py", "tests/test_engine.py", "README.md"], "description": "Tests and docs"},
            ],
        },
        "discord_bot": {
            "name": "Discord Bot",
            "description": "Discord bot with slash commands, event handling, database, and modular cogs",
            "estimated_credits": {"min": 10, "max": 20},
            "stack": {
                "language": "Python 3.12",
                "framework": "discord.py 2.x",
                "database": "SQLite + aiosqlite",
                "config": "python-dotenv",
            },
            "file_tree": {
                "pyproject.toml": "config",
                ".env.example": "config",
                "bot/__init__.py": "config",
                "bot/config.py": "config",
                "bot/database.py": "model",
                "bot/models.py": "model",
                "bot/main.py": "router",
                "bot/cogs/__init__.py": "config",
                "bot/cogs/general.py": "service",
                "bot/cogs/moderation.py": "service",
                "bot/cogs/fun.py": "service",
                "bot/cogs/admin.py": "service",
                "bot/utils/embeds.py": "util",
                "bot/utils/permissions.py": "util",
                "tests/test_cogs.py": "test",
                "tests/conftest.py": "test",
                "Dockerfile": "docker",
            },
            "phases": [
                {"name": "Config & Data", "files": ["pyproject.toml", ".env.example", "bot/__init__.py", "bot/config.py", "bot/database.py", "bot/models.py"], "description": "Setup and data layer"},
                {"name": "Utilities", "files": ["bot/utils/embeds.py", "bot/utils/permissions.py", "bot/cogs/__init__.py"], "description": "Shared utilities"},
                {"name": "Cogs", "files": ["bot/cogs/general.py", "bot/cogs/moderation.py", "bot/cogs/fun.py", "bot/cogs/admin.py"], "description": "Bot command modules"},
                {"name": "Entry & Tests", "files": ["bot/main.py", "tests/conftest.py", "tests/test_cogs.py", "Dockerfile"], "description": "Entrypoint and tests"},
            ],
        },
        "data_pipeline": {
            "name": "Data Pipeline",
            "description": "ETL data pipeline with ingestion, transformation, validation, and scheduling",
            "estimated_credits": {"min": 12, "max": 22},
            "stack": {
                "language": "Python 3.12",
                "data": "Pandas + Polars",
                "storage": "PostgreSQL + S3 (boto3)",
                "scheduling": "APScheduler",
                "testing": "pytest",
            },
            "file_tree": {
                "pyproject.toml": "config",
                "config/settings.py": "config",
                "config/logging.py": "config",
                "pipeline/__init__.py": "config",
                "pipeline/models.py": "model",
                "pipeline/database.py": "model",
                "pipeline/ingestion/base.py": "service",
                "pipeline/ingestion/csv_source.py": "service",
                "pipeline/ingestion/api_source.py": "service",
                "pipeline/transform/base.py": "service",
                "pipeline/transform/cleaner.py": "service",
                "pipeline/transform/enricher.py": "service",
                "pipeline/validation/schema_validator.py": "service",
                "pipeline/validation/quality_checks.py": "service",
                "pipeline/output/db_writer.py": "service",
                "pipeline/output/s3_writer.py": "service",
                "pipeline/orchestrator.py": "router",
                "pipeline/scheduler.py": "router",
                "pipeline/main.py": "router",
                "tests/test_ingestion.py": "test",
                "tests/test_transform.py": "test",
                "tests/test_validation.py": "test",
                "tests/conftest.py": "test",
                "Dockerfile": "docker",
            },
            "phases": [
                {"name": "Config", "files": ["pyproject.toml", "config/settings.py", "config/logging.py", "pipeline/__init__.py", "pipeline/models.py", "pipeline/database.py"], "description": "Configuration and data models"},
                {"name": "Ingestion", "files": ["pipeline/ingestion/base.py", "pipeline/ingestion/csv_source.py", "pipeline/ingestion/api_source.py"], "description": "Data sources"},
                {"name": "Transform", "files": ["pipeline/transform/base.py", "pipeline/transform/cleaner.py", "pipeline/transform/enricher.py"], "description": "Data transformation"},
                {"name": "Validation & Output", "files": ["pipeline/validation/schema_validator.py", "pipeline/validation/quality_checks.py", "pipeline/output/db_writer.py", "pipeline/output/s3_writer.py"], "description": "Data validation and output writers"},
                {"name": "Orchestration", "files": ["pipeline/orchestrator.py", "pipeline/scheduler.py", "pipeline/main.py"], "description": "Pipeline orchestration"},
                {"name": "Tests & Deploy", "files": ["tests/conftest.py", "tests/test_ingestion.py", "tests/test_transform.py", "tests/test_validation.py", "Dockerfile"], "description": "Tests and deployment"},
            ],
        },
        "mobile_api": {
            "name": "Mobile API Backend",
            "description": "Backend API optimized for mobile apps with push notifications, file uploads, and versioning",
            "estimated_credits": {"min": 18, "max": 35},
            "stack": {
                "backend": "FastAPI + Python 3.12",
                "database": "PostgreSQL + SQLAlchemy",
                "cache": "Redis",
                "storage": "S3 (boto3)",
                "push": "Firebase Cloud Messaging",
                "deployment": "Docker",
            },
            "file_tree": {
                "pyproject.toml": "config",
                "app/__init__.py": "config",
                "app/config.py": "config",
                "app/database.py": "config",
                "app/models/__init__.py": "model",
                "app/models/user.py": "model",
                "app/models/device.py": "model",
                "app/models/notification.py": "model",
                "app/models/upload.py": "model",
                "app/schemas/user.py": "schema",
                "app/schemas/device.py": "schema",
                "app/schemas/notification.py": "schema",
                "app/schemas/upload.py": "schema",
                "app/services/auth_service.py": "service",
                "app/services/push_service.py": "service",
                "app/services/upload_service.py": "service",
                "app/services/cache_service.py": "service",
                "app/api/v1/__init__.py": "config",
                "app/api/v1/auth.py": "router",
                "app/api/v1/users.py": "router",
                "app/api/v1/devices.py": "router",
                "app/api/v1/notifications.py": "router",
                "app/api/v1/uploads.py": "router",
                "app/middleware/auth.py": "middleware",
                "app/middleware/versioning.py": "middleware",
                "app/main.py": "router",
                "tests/test_auth.py": "test",
                "tests/test_uploads.py": "test",
                "tests/conftest.py": "test",
                "Dockerfile": "docker",
                "docker-compose.yml": "docker",
            },
            "phases": [
                {"name": "Config", "files": ["pyproject.toml", "app/__init__.py", "app/config.py", "app/database.py", "app/api/v1/__init__.py"], "description": "Configuration"},
                {"name": "Models", "files": ["app/models/__init__.py", "app/models/user.py", "app/models/device.py", "app/models/notification.py", "app/models/upload.py"], "description": "Database models"},
                {"name": "Schemas", "files": ["app/schemas/user.py", "app/schemas/device.py", "app/schemas/notification.py", "app/schemas/upload.py"], "description": "API schemas"},
                {"name": "Services", "files": ["app/services/auth_service.py", "app/services/push_service.py", "app/services/upload_service.py", "app/services/cache_service.py"], "description": "Business logic"},
                {"name": "Middleware & API", "files": ["app/middleware/auth.py", "app/middleware/versioning.py", "app/api/v1/auth.py", "app/api/v1/users.py", "app/api/v1/devices.py", "app/api/v1/notifications.py", "app/api/v1/uploads.py", "app/main.py"], "description": "API endpoints"},
                {"name": "Tests & Deploy", "files": ["tests/conftest.py", "tests/test_auth.py", "tests/test_uploads.py", "Dockerfile", "docker-compose.yml"], "description": "Tests and deployment"},
            ],
        },
        "ecommerce": {
            "name": "E-Commerce Platform",
            "description": "Full e-commerce backend with products, cart, orders, payments, and admin",
            "estimated_credits": {"min": 30, "max": 55},
            "stack": {
                "frontend": "Next.js 14 + TypeScript + Tailwind CSS",
                "backend": "FastAPI + Python 3.12",
                "database": "PostgreSQL + SQLAlchemy",
                "payments": "Stripe",
                "search": "Full-text PostgreSQL search",
                "deployment": "Docker + Docker Compose",
            },
            "file_tree": {
                "backend/pyproject.toml": "config",
                "backend/app/__init__.py": "config",
                "backend/app/config.py": "config",
                "backend/app/database.py": "config",
                "backend/app/models/__init__.py": "model",
                "backend/app/models/user.py": "model",
                "backend/app/models/product.py": "model",
                "backend/app/models/category.py": "model",
                "backend/app/models/cart.py": "model",
                "backend/app/models/order.py": "model",
                "backend/app/models/review.py": "model",
                "backend/app/schemas/user.py": "schema",
                "backend/app/schemas/product.py": "schema",
                "backend/app/schemas/cart.py": "schema",
                "backend/app/schemas/order.py": "schema",
                "backend/app/services/auth_service.py": "service",
                "backend/app/services/product_service.py": "service",
                "backend/app/services/cart_service.py": "service",
                "backend/app/services/order_service.py": "service",
                "backend/app/services/payment_service.py": "service",
                "backend/app/services/search_service.py": "service",
                "backend/app/api/auth.py": "router",
                "backend/app/api/products.py": "router",
                "backend/app/api/cart.py": "router",
                "backend/app/api/orders.py": "router",
                "backend/app/api/admin.py": "router",
                "backend/app/api/webhooks.py": "router",
                "backend/app/middleware/auth.py": "middleware",
                "backend/app/main.py": "router",
                "backend/tests/test_products.py": "test",
                "backend/tests/test_orders.py": "test",
                "backend/tests/conftest.py": "test",
                "backend/Dockerfile": "docker",
                "frontend/package.json": "config",
                "frontend/app/layout.tsx": "page",
                "frontend/app/page.tsx": "page",
                "frontend/app/products/page.tsx": "page",
                "frontend/app/products/[id]/page.tsx": "page",
                "frontend/app/cart/page.tsx": "page",
                "frontend/app/checkout/page.tsx": "page",
                "frontend/app/orders/page.tsx": "page",
                "frontend/components/ProductCard.tsx": "component",
                "frontend/components/CartDrawer.tsx": "component",
                "frontend/components/CheckoutForm.tsx": "component",
                "frontend/hooks/useCart.ts": "hook",
                "frontend/hooks/useProducts.ts": "hook",
                "frontend/lib/api.ts": "service",
                "frontend/Dockerfile": "docker",
                "docker-compose.yml": "docker",
            },
            "phases": [
                {"name": "Config", "files": ["backend/pyproject.toml", "backend/app/__init__.py", "backend/app/config.py", "backend/app/database.py", "frontend/package.json"], "description": "Project configuration"},
                {"name": "Models", "files": ["backend/app/models/__init__.py", "backend/app/models/user.py", "backend/app/models/product.py", "backend/app/models/category.py", "backend/app/models/cart.py", "backend/app/models/order.py", "backend/app/models/review.py"], "description": "Database models"},
                {"name": "Schemas", "files": ["backend/app/schemas/user.py", "backend/app/schemas/product.py", "backend/app/schemas/cart.py", "backend/app/schemas/order.py"], "description": "API schemas"},
                {"name": "Services", "files": ["backend/app/services/auth_service.py", "backend/app/services/product_service.py", "backend/app/services/cart_service.py", "backend/app/services/order_service.py", "backend/app/services/payment_service.py", "backend/app/services/search_service.py"], "description": "Business logic"},
                {"name": "Backend API", "files": ["backend/app/middleware/auth.py", "backend/app/api/auth.py", "backend/app/api/products.py", "backend/app/api/cart.py", "backend/app/api/orders.py", "backend/app/api/admin.py", "backend/app/api/webhooks.py", "backend/app/main.py"], "description": "API endpoints"},
                {"name": "Frontend Foundation", "files": ["frontend/lib/api.ts", "frontend/hooks/useCart.ts", "frontend/hooks/useProducts.ts", "frontend/components/ProductCard.tsx", "frontend/components/CartDrawer.tsx", "frontend/components/CheckoutForm.tsx"], "description": "Frontend data layer and components"},
                {"name": "Frontend Pages", "files": ["frontend/app/layout.tsx", "frontend/app/page.tsx", "frontend/app/products/page.tsx", "frontend/app/products/[id]/page.tsx", "frontend/app/cart/page.tsx", "frontend/app/checkout/page.tsx", "frontend/app/orders/page.tsx"], "description": "Application pages"},
                {"name": "Tests & Deploy", "files": ["backend/tests/conftest.py", "backend/tests/test_products.py", "backend/tests/test_orders.py", "backend/Dockerfile", "frontend/Dockerfile", "docker-compose.yml"], "description": "Tests and deployment"},
            ],
        },
    }

    # Keywords for template matching
    _TEMPLATE_KEYWORDS: dict[str, list[str]] = {
        "saas_starter": ["saas", "subscription", "multi-tenant", "billing dashboard", "saas boilerplate", "saas starter"],
        "rest_api": ["rest api", "api", "crud", "backend api", "json api", "restful"],
        "react_app": ["react", "frontend", "single page", "spa", "react app", "vite react"],
        "cli_tool": ["cli", "command line", "terminal", "command-line tool", "cli tool"],
        "discord_bot": ["discord", "bot", "discord bot", "chat bot"],
        "data_pipeline": ["etl", "pipeline", "data pipeline", "data processing", "ingestion", "data engineering"],
        "mobile_api": ["mobile", "mobile api", "mobile backend", "push notification", "app backend"],
        "ecommerce": ["ecommerce", "e-commerce", "shop", "store", "cart", "checkout", "products"],
    }

    def get_template(self, key: str) -> dict | None:
        """Return a template by key, or None if not found."""
        return self.TEMPLATES.get(key)

    def match_template(self, description: str) -> str | None:
        """Simple keyword matching to find the best template for a description.

        Returns the template key or None if no match exceeds the threshold.
        """
        desc_lower = description.lower()
        best_key: str | None = None
        best_score = 0

        for template_key, keywords in self._TEMPLATE_KEYWORDS.items():
            score = 0
            for keyword in keywords:
                if keyword in desc_lower:
                    # Longer keyword matches are worth more
                    score += len(keyword.split())
            if score > best_score:
                best_score = score
                best_key = template_key

        # Require at least one multi-word match or two single-word matches
        if best_score >= 2:
            return best_key

        return None

    def list_templates(self) -> list[dict]:
        """Return summary info for all available templates."""
        result: list[dict] = []
        for key, template in self.TEMPLATES.items():
            result.append({
                "key": key,
                "name": template["name"],
                "description": template["description"],
                "estimated_credits": template["estimated_credits"],
                "file_count": len(template["file_tree"]),
                "phase_count": len(template["phases"]),
            })
        return result
